import React,{useEffect} from 'react';
//import Clipboard from '@react-native-clipboard/clipboard';
//import {API} from '../apis/index.js';
import { ImageBackground,StyleSheet, Image, SafeAreaView, Text, TextInput,View, Linking, Button, Alert,Clipboard, TouchableOpacity, ScrollView} from 'react-native';
import axios from 'axios';
const CampDetail=()=>{
    
    //TODO: 전화번호 넘겨받고 넘겨주기
    const callAlert = () =>{
        Alert.alert( '010-XXXX-XXXX',"",[
            {
                text: '전화걸기',
                onPress: ()=> {Linking.openURL(`tel:01000000000`)},

            },
            {
                text: '클립보드에 복사하기',
                // TODO: 클립보드 기능
                onPress: () => console.log('클립보드에 복사하기'),
            },
            {
                text:'취소',
                onPress: () => console.log('Cancel Pressed'),
                style: 'cancel',
            },
        ]);
    }
    //TODO: 클립보드 기능2
    // const copyToClipboard=()=>{
    //     Clipboard.setString('hello world');
    // };

//TODO: API연결

    const serviceKey='TseWf5%2BGtqbeYPvniw22jUCsTdxa7%2BX%2BXHaw0%2BtgbRID7LWSIBQGrE9AzfSiyVkyd42wsTBzDheTkd1OPQkbtw%3D%3D';
    
    useEffect(()=>{
        getList();
    },[]);

    const getList=async()=>{
        try{
            const res = await axios (`http://apis.data.go.kr/B551011/GoCamping/basedList?numOfRows=5&pageNo=1&MobileOS=IOS&MobileApp=camping&serviceKey=${serviceKey}&_type=json`,);
            console.log(res);
        }
        catch(error){
            console.error(error);
        }
    };


        

    return(
        
        <SafeAreaView style={{flex:1,}}>
            <ImageBackground source={require('@images/backgroundImg.png')} resizeMode='cover'  >
                {/* TODO: 헤더 컴포넌트로 분리, 가운데 정렬 해결필요 */}
                <View style={styles.headerArea}> 
                    <TouchableOpacity style={{backgroundColor:"#fff"}}>
                        <Image source={require('@icons/leftArrow.png')}/>
                    </TouchableOpacity>
                    <Text style={{ color:"#573353",fontSize:18, fontWeight:'bold', backgroundColor:"#000"}}>캠핑장 상세정보</Text>
                </View>
                <View style={{width:100}}>
                    <Image source={require('@images/dummyCampImg.png')}/> 
                
                </View>
                <View style={{paddingHorizontal:15}}>
                    <View>
                        <Text style={{color:'#FC9D45', fontWeight:'bold',paddingTop:38, paddingBottom:8,fontSize:13}}>민간|직영</Text>
                    </View>
                    <View>
                        <Text style={{fontSize:16, fontWeight:'bold',paddingBottom:10}}>(주)아웃오브파크</Text>
                    </View>
                    <View>
                        <Text style={{fontSize:13, fontWeight:'bold',paddingBottom:10, color:"#707070"}}>addr1: 강원도 춘천시 남면 가옹개길 52-9</Text>
                    </View>
                    <View>
                        <Text style={{fontSize:16, fontWeight:'bold',paddingBottom:10}}>sbrsCl: 침대,TV,에어컨,냉장고,난방기구,취사도구,내부화장실</Text>
                    </View>
                    <View>
                        <Text style={{color:'#919191', fontWeight:'bold', fontSize:15,paddingBottom:10 }}>소개 및 안내</Text>
                    </View>
                    
                    <ScrollView>
                        <Text>featureNm: 아웃오브파트는 강원도 춘천시 남면에 자리했다. 서울양양고속도로 강촌IC에서 엘리시안강촌 방면으로 30분가량 달리면 도착한다. 이곳은 북한강 변의 수려한 풍광을 배경으로 캐러밴 40대가 들어찼다. 고급스러움이 돋보이는 유럽피안 캐러밴과 에어스트림 캐러밴이다. 모든 캐러밴은 각기 다른 주제로 꾸몄다. 이 덕분에 욕실에 중점을 둔 객실이나 침실에 초점을 맞춘 객실 등 취향에 따라 선택하는 재미가 있다. 외부에는 어닝 아래 테이블, 의자, 노천욕탕, 바비큐 시설을 마련했다. 캠핑장의 강점 중 하나는 부대시설이다. 카페, 수영장, 찜질방, 스파, 중앙 무대, 분수, 노래방 등 고급스러움으로 치장한 시설이 차고 넘친다.</Text>
                    </ScrollView>
                </View>
                {/* TODO: 버튼 바탕색 바꾸기, 화면 하단에 고정되게 */}
                <Button  onPress= {()=>callAlert()}title='전화걸기'></Button>
            </ImageBackground>
        </SafeAreaView>
    );
}

export default CampDetail;
const styles = StyleSheet.create({
    headerArea:{
        backgroundColor:"#FFF3E9",
        paddingHorizontal:15,
        alignItems:'center',
        flexDirection:'row'

    },
    callBtn:{
        backgroundColor:"#FDA758"
    }
})
// const dummyList = 
// {
//     "response": {
//       "header": {
//         "resultCode": "0000",
//         "resultMsg": "OK"
//       },
//       "body": {
//         "items": {
//           "item": [
//             {
//               "contentId": "100193",
//               "facltNm": "선장포협동조합",
//               "lineIntro": "",
//               "intro": "",
//               "allar": "0",
//               "insrncAt": "Y",
//               "trsagntNo": "",
//               "bizrno": "",
//               "facltDivNm": "민간",
//               "mangeDivNm": "직영",
//               "mgcDiv": "",
//               "manageSttus": "운영",
//               "hvofBgnde": "",
//               "hvofEnddle": "",
//               "featureNm": "삽교천의 풍광이 눈앞에 펼쳐지는 캠핑장  선장포협동조합은 충남 아산시 선장면 군덕리 소재 선장포노을공원에 자리 잡았다. 아산시청을 기점으로 20km가량 떨어졌다. 자동차를 타고 아산로와 충절로를 번갈아 달리면 닿는다. 도착까지 걸리는 시간은 20분 안팎이다. 삽교천의 멋진 풍경이 펼쳐지는 캠핑장에는 잔디블록으로 이뤄진 일반캠핑 사이트 25면이 마련돼 있다. 이 가운데 텐트 설치가 가능한 12면은 가로 7m 세로 6m다. 카라반, 트레일러가 입장할 수 있는 13면은 가로 6m 세로 4m다. 주변에는 도고온천이 있어 연계 관광이 손쉽다.",
//               "induty": "자동차야영장",
//               "lctCl": "강",
//               "doNm": "충청남도",
//               "sigunguNm": "아산시",
//               "zipcode": "31546",
//               "addr1": "충남 아산시 선장면 선장로 121-10",
//               "addr2": "",
//               "mapX": "126.8595945",
//               "mapY": "36.7903534",
//               "direction": "",
//               "tel": "070-7797-0104",
//               "homepage": "https://blog.naver.com/seonjangnoel",
//               "resveUrl": "https://booking.naver.com/booking/3/bizes/629226",
//               "resveCl": "온라인실시간예약",
//               "manageNmpr": "1",
//               "gnrlSiteCo": "25",
//               "autoSiteCo": "0",
//               "glampSiteCo": "0",
//               "caravSiteCo": "0",
//               "indvdlCaravSiteCo": "0",
//               "sitedStnc": "3",
//               "siteMg1Width": "0",
//               "siteMg2Width": "0",
//               "siteMg3Width": "0",
//               "siteMg1Vrticl": "0",
//               "siteMg2Vrticl": "0",
//               "siteMg3Vrticl": "0",
//               "siteMg1Co": "12",
//               "siteMg2Co": "13",
//               "siteMg3Co": "0",
//               "siteBottomCl1": "25",
//               "siteBottomCl2": "0",
//               "siteBottomCl3": "0",
//               "siteBottomCl4": "0",
//               "siteBottomCl5": "0",
//               "tooltip": "",
//               "glampInnerFclty": "",
//               "caravInnerFclty": "",
//               "prmisnDe": "2021-11-22",
//               "operPdCl": "봄,여름,가을,겨울",
//               "operDeCl": "평일+주말",
//               "trlerAcmpnyAt": "Y",
//               "caravAcmpnyAt": "N",
//               "toiletCo": "2",
//               "swrmCo": "2",
//               "wtrplCo": "1",
//               "brazierCl": "개별",
//               "sbrsCl": "전기,온수,놀이터,운동장,운동시설,마트.편의점",
//               "sbrsEtc": "",
//               "posblFcltyCl": "산책로",
//               "posblFcltyEtc": "",
//               "clturEventAt": "N",
//               "clturEvent": "",
//               "exprnProgrmAt": "N",
//               "exprnProgrm": "",
//               "extshrCo": "15",
//               "frprvtWrppCo": "0",
//               "frprvtSandCo": "0",
//               "fireSensorCo": "0",
//               "themaEnvrnCl": "",
//               "eqpmnLendCl": "",
//               "animalCmgCl": "가능",
//               "tourEraCl": "",
//               "firstImageUrl": "https://gocamping.or.kr/upload/camp/100193/thumb/thumb_720_02321tB7RbjvfYxJdFG4HP5e.jpg",
//               "createdtime": "2023-01-16 16:49:14",
//               "modifiedtime": "2023-01-16 16:49:14"
//             },
//             {
//               "contentId": "100194",
//               "facltNm": "더존 관광농원",
//               "lineIntro": "",
//               "intro": "야외수영장과 넓은 잔디운동장, 아이들과 함께 즐겁고 편안하게 휴식할 수 있는 공간",
//               "allar": "10560",
//               "insrncAt": "Y",
//               "trsagntNo": "2021-15",
//               "bizrno": "",
//               "facltDivNm": "민간",
//               "mangeDivNm": "직영",
//               "mgcDiv": "",
//               "manageSttus": "운영",
//               "hvofBgnde": "",
//               "hvofEnddle": "",
//               "featureNm": "럭셔리 수영장, 넓은 잔디 운동장을 갖춘 리조트형 글램핑과 카라반  이동갈비촌 안쪽 이동중학교 건너편에 위치한 워터 리조트형 글램핑장이다. 제대로 된 대형 수영장에 워터슬라이드까지 갖추고 있어 여름 물놀이를 겸한 캠핑에 좋은 곳이다. 수영장은 입구 쪽에 있고, 캠핑 사이트들과 떨어져 시끄럽지 않도록 배치되어 있다. 일반 캠핑 사이트는 없고, 카라반과 글램핑만 총 28개가 있다. 요금이 저렴하진 않지만, 시설이 잘 갖추어져서 편리하다. 산으로 둘러싸인 넓은 잔디광장에 여유롭게 배치되어 있어 탁 트인 자연 속에 독립된 느낌으로 캠핑을 즐길 수 있다. 캠핑장 바로위에 국망봉 자연휴양림이 있다.",
//               "induty": "카라반,글램핑",
//               "lctCl": "산",
//               "doNm": "경기도",
//               "sigunguNm": "포천시",
//               "zipcode": "11111",
//               "addr1": "경기 포천시 이동면 화동로2076번길 125",
//               "addr2": "",
//               "mapX": "127.3803955",
//               "mapY": "38.0327484",
//               "direction": "",
//               "tel": "010-8883-8902",
//               "homepage": "http://duzoncaravan.com/",
//               "resveUrl": "",
//               "resveCl": "온라인실시간예약",
//               "manageNmpr": "0",
//               "gnrlSiteCo": "0",
//               "autoSiteCo": "0",
//               "glampSiteCo": "10",
//               "caravSiteCo": "20",
//               "indvdlCaravSiteCo": "0",
//               "sitedStnc": "0",
//               "siteMg1Width": "0",
//               "siteMg2Width": "0",
//               "siteMg3Width": "0",
//               "siteMg1Vrticl": "0",
//               "siteMg2Vrticl": "0",
//               "siteMg3Vrticl": "0",
//               "siteMg1Co": "0",
//               "siteMg2Co": "0",
//               "siteMg3Co": "0",
//               "siteBottomCl1": "0",
//               "siteBottomCl2": "0",
//               "siteBottomCl3": "0",
//               "siteBottomCl4": "0",
//               "siteBottomCl5": "0",
//               "tooltip": "",
//               "glampInnerFclty": "침대,TV,에어컨,냉장고,유무선인터넷,난방기구,취사도구,내부화장실,내부샤워실",
//               "caravInnerFclty": "침대,TV,에어컨,냉장고,유무선인터넷,난방기구,취사도구,내부화장실,내부샤워실",
//               "prmisnDe": "2021-11-24",
//               "operPdCl": "봄,여름,가을,겨울",
//               "operDeCl": "평일+주말",
//               "trlerAcmpnyAt": "N",
//               "caravAcmpnyAt": "N",
//               "toiletCo": "5",
//               "swrmCo": "10",
//               "wtrplCo": "1",
//               "brazierCl": "개별",
//               "sbrsCl": "전기,무선인터넷,장작판매,온수,트렘폴린,물놀이장,운동시설,마트.편의점",
//               "sbrsEtc": "",
//               "posblFcltyCl": "",
//               "posblFcltyEtc": "",
//               "clturEventAt": "N",
//               "clturEvent": "",
//               "exprnProgrmAt": "N",
//               "exprnProgrm": "",
//               "extshrCo": "31",
//               "frprvtWrppCo": "0",
//               "frprvtSandCo": "0",
//               "fireSensorCo": "29",
//               "themaEnvrnCl": "가을단풍명소",
//               "eqpmnLendCl": "화로대",
//               "animalCmgCl": "불가능",
//               "tourEraCl": "여름",
//               "firstImageUrl": "https://gocamping.or.kr/upload/camp/100194/thumb/thumb_720_1836NBL1hGcaiiZlIASO67id.jpg",
//               "createdtime": "2023-01-16 16:49:14",
//               "modifiedtime": "2023-01-16 16:49:14"
//             },
//             {
//               "contentId": "100195",
//               "facltNm": "물바람캠핑장",
//               "lineIntro": "",
//               "intro": "",
//               "allar": "0",
//               "insrncAt": "Y",
//               "trsagntNo": "",
//               "bizrno": "",
//               "facltDivNm": "민간",
//               "mangeDivNm": "직영",
//               "mgcDiv": "",
//               "manageSttus": "운영",
//               "hvofBgnde": "",
//               "hvofEnddle": "",
//               "featureNm": "",
//               "induty": "일반야영장",
//               "lctCl": "",
//               "doNm": "전라북도",
//               "sigunguNm": "완주군",
//               "zipcode": "55344",
//               "addr1": "전북 완주군 동상면 송광수만로 1079-61",
//               "addr2": "",
//               "mapX": "127.2641587",
//               "mapY": "35.9291573",
//               "direction": "",
//               "tel": "",
//               "homepage": "",
//               "resveUrl": "",
//               "resveCl": "",
//               "manageNmpr": "0",
//               "gnrlSiteCo": "0",
//               "autoSiteCo": "0",
//               "glampSiteCo": "0",
//               "caravSiteCo": "0",
//               "indvdlCaravSiteCo": "0",
//               "sitedStnc": "0",
//               "siteMg1Width": "0",
//               "siteMg2Width": "0",
//               "siteMg3Width": "0",
//               "siteMg1Vrticl": "0",
//               "siteMg2Vrticl": "0",
//               "siteMg3Vrticl": "0",
//               "siteMg1Co": "0",
//               "siteMg2Co": "0",
//               "siteMg3Co": "0",
//               "siteBottomCl1": "0",
//               "siteBottomCl2": "0",
//               "siteBottomCl3": "0",
//               "siteBottomCl4": "0",
//               "siteBottomCl5": "0",
//               "tooltip": "",
//               "glampInnerFclty": "",
//               "caravInnerFclty": "",
//               "prmisnDe": "2021-11-26",
//               "operPdCl": "봄,여름,가을,겨울",
//               "operDeCl": "평일+주말",
//               "trlerAcmpnyAt": "N",
//               "caravAcmpnyAt": "N",
//               "toiletCo": "0",
//               "swrmCo": "0",
//               "wtrplCo": "0",
//               "brazierCl": "개별",
//               "sbrsCl": "",
//               "sbrsEtc": "",
//               "posblFcltyCl": "",
//               "posblFcltyEtc": "",
//               "clturEventAt": "N",
//               "clturEvent": "",
//               "exprnProgrmAt": "N",
//               "exprnProgrm": "",
//               "extshrCo": "0",
//               "frprvtWrppCo": "0",
//               "frprvtSandCo": "0",
//               "fireSensorCo": "0",
//               "themaEnvrnCl": "",
//               "eqpmnLendCl": "",
//               "animalCmgCl": "불가능",
//               "tourEraCl": "",
//               "firstImageUrl": "",
//               "createdtime": "2023-01-16 16:49:14",
//               "modifiedtime": "2023-01-16 16:49:14"
//             },
//             {
//               "contentId": "100196",
//               "facltNm": "을왕리 솔트 캠핑장",
//               "lineIntro": "",
//               "intro": "",
//               "allar": "0",
//               "insrncAt": "Y",
//               "trsagntNo": "",
//               "bizrno": "",
//               "facltDivNm": "민간",
//               "mangeDivNm": "직영",
//               "mgcDiv": "",
//               "manageSttus": "운영",
//               "hvofBgnde": "",
//               "hvofEnddle": "",
//               "featureNm": "영종도 왕산 해수욕장 내 멋진 소나무 숲 캠핑장  인천 영종도 왕산 해수욕장 내의 멋진 소나무 숲과 어우러진 캠핑장이다. 서울 근교로 접근성이 좋고 최근 신축되어 시설이 깨끗하여 편리하다. 캠핑장은 크게 차박용 구역, 애견 출입 가능한 캠핑장 구역, 카라반 구역으로 나눠져 있다. 캠핑 사이트는 파쇄석으로 되어 있고, 주차 공간이 넉넉하다. 바로 앞 왕산 해수욕장은 도보 1분 거리로, 주변에 편의점, 식당, 카페 등 시설들도 있어서, 여름철 온가 족이 해수욕과 캠핑을 즐기기에 최적의 캠핑장이다.",
//               "induty": "자동차야영장",
//               "lctCl": "해변",
//               "doNm": "인천시",
//               "sigunguNm": "중구",
//               "zipcode": "22383",
//               "addr1": "인천 중구 용유서로423번길 38 (을왕동)",
//               "addr2": "",
//               "mapX": "126.3689413",
//               "mapY": "37.4576530",
//               "direction": "",
//               "tel": "033-751-9300",
//               "homepage": "https://saltcamping.modoo.at",
//               "resveUrl": "",
//               "resveCl": "온라인실시간예약",
//               "manageNmpr": "0",
//               "gnrlSiteCo": "30",
//               "autoSiteCo": "0",
//               "glampSiteCo": "0",
//               "caravSiteCo": "0",
//               "indvdlCaravSiteCo": "0",
//               "sitedStnc": "0",
//               "siteMg1Width": "0",
//               "siteMg2Width": "0",
//               "siteMg3Width": "0",
//               "siteMg1Vrticl": "0",
//               "siteMg2Vrticl": "0",
//               "siteMg3Vrticl": "0",
//               "siteMg1Co": "30",
//               "siteMg2Co": "0",
//               "siteMg3Co": "0",
//               "siteBottomCl1": "0",
//               "siteBottomCl2": "30",
//               "siteBottomCl3": "0",
//               "siteBottomCl4": "0",
//               "siteBottomCl5": "0",
//               "tooltip": "",
//               "glampInnerFclty": "",
//               "caravInnerFclty": "",
//               "prmisnDe": "2021-11-26",
//               "operPdCl": "봄,여름,가을,겨울",
//               "operDeCl": "평일+주말",
//               "trlerAcmpnyAt": "Y",
//               "caravAcmpnyAt": "N",
//               "toiletCo": "1",
//               "swrmCo": "1",
//               "wtrplCo": "1",
//               "brazierCl": "개별",
//               "sbrsCl": "전기,무선인터넷,장작판매,온수",
//               "sbrsEtc": "",
//               "posblFcltyCl": "해수욕",
//               "posblFcltyEtc": "",
//               "clturEventAt": "N",
//               "clturEvent": "",
//               "exprnProgrmAt": "N",
//               "exprnProgrm": "",
//               "extshrCo": "0",
//               "frprvtWrppCo": "0",
//               "frprvtSandCo": "0",
//               "fireSensorCo": "0",
//               "themaEnvrnCl": "일몰명소,여름물놀이",
//               "eqpmnLendCl": "",
//               "animalCmgCl": "가능(소형견)",
//               "tourEraCl": "",
//               "firstImageUrl": "https://gocamping.or.kr/upload/camp/100196/thumb/thumb_720_31567o5YSxlqo6VdAqvLYUAX.jpg",
//               "createdtime": "2023-01-16 16:49:14",
//               "modifiedtime": "2023-01-16 16:49:14"
//             },
//             {
//               "contentId": "100197",
//               "facltNm": "(주)백동소풍가는길",
//               "lineIntro": "",
//               "intro": "",
//               "allar": "0",
//               "insrncAt": "Y",
//               "trsagntNo": "",
//               "bizrno": "",
//               "facltDivNm": "민간",
//               "mangeDivNm": "직영",
//               "mgcDiv": "",
//               "manageSttus": "운영",
//               "hvofBgnde": "",
//               "hvofEnddle": "",
//               "featureNm": "",
//               "induty": "일반야영장",
//               "lctCl": "",
//               "doNm": "경상남도",
//               "sigunguNm": "양산시",
//               "zipcode": "50517",
//               "addr1": "경남 양산시 백동길 128 (소주동)",
//               "addr2": "",
//               "mapX": "129.1443610",
//               "mapY": "35.4037221",
//               "direction": "",
//               "tel": "055-389-0127",
//               "homepage": "",
//               "resveUrl": "",
//               "resveCl": "",
//               "manageNmpr": "0",
//               "gnrlSiteCo": "0",
//               "autoSiteCo": "0",
//               "glampSiteCo": "0",
//               "caravSiteCo": "0",
//               "indvdlCaravSiteCo": "0",
//               "sitedStnc": "0",
//               "siteMg1Width": "0",
//               "siteMg2Width": "0",
//               "siteMg3Width": "0",
//               "siteMg1Vrticl": "0",
//               "siteMg2Vrticl": "0",
//               "siteMg3Vrticl": "0",
//               "siteMg1Co": "0",
//               "siteMg2Co": "0",
//               "siteMg3Co": "0",
//               "siteBottomCl1": "0",
//               "siteBottomCl2": "0",
//               "siteBottomCl3": "0",
//               "siteBottomCl4": "0",
//               "siteBottomCl5": "0",
//               "tooltip": "",
//               "glampInnerFclty": "",
//               "caravInnerFclty": "",
//               "prmisnDe": "2021-11-30",
//               "operPdCl": "봄,여름,가을,겨울",
//               "operDeCl": "평일+주말",
//               "trlerAcmpnyAt": "N",
//               "caravAcmpnyAt": "N",
//               "toiletCo": "0",
//               "swrmCo": "0",
//               "wtrplCo": "0",
//               "brazierCl": "개별",
//               "sbrsCl": "",
//               "sbrsEtc": "",
//               "posblFcltyCl": "",
//               "posblFcltyEtc": "",
//               "clturEventAt": "N",
//               "clturEvent": "",
//               "exprnProgrmAt": "N",
//               "exprnProgrm": "",
//               "extshrCo": "0",
//               "frprvtWrppCo": "0",
//               "frprvtSandCo": "0",
//               "fireSensorCo": "0",
//               "themaEnvrnCl": "",
//               "eqpmnLendCl": "",
//               "animalCmgCl": "불가능",
//               "tourEraCl": "",
//               "firstImageUrl": "",
//               "createdtime": "2023-01-16 16:49:14",
//               "modifiedtime": "2023-01-16 16:49:14"
//             },
//             {
//               "contentId": "100198",
//               "facltNm": "오아시스정글",
//               "lineIntro": "",
//               "intro": "",
//               "allar": "0",
//               "insrncAt": "Y",
//               "trsagntNo": "",
//               "bizrno": "",
//               "facltDivNm": "민간",
//               "mangeDivNm": "직영",
//               "mgcDiv": "",
//               "manageSttus": "운영",
//               "hvofBgnde": "",
//               "hvofEnddle": "",
//               "featureNm": "필례 게르마늄 온천에 마련된 캠핑장   한계령에서 점봉산을 넘어 인제로 이어지는 고개 중간에 위치한 필례게르마늄 온천에 마련된 캠핑장이다.  700m 지하 깊숙한 곳에서 올라오는 100% 천연 온천수를 제공하는 온천시설인 필례 온천은 아토피 및 탈모 완하에 효과가 있다는 게르마늄의 함량이 국내 최고이자 세계 2위라고 한다. 캠핑장 고객은 래프팅, 사륜 오토바이 투어, 낙산 해수욕장 모터 보팅 등의 레포츠도 예약 시 할인가로 즐길 수 있다. 특히 자작나무 숲 속에 있는 사이트가 인기다. 조용히 힐링할 수 있는 폭포 및 숲 산책로가 주변에 있고, 인근 관광지로는 백담사와 낙산 해변, 내린천 수변공원 등이 있다.",
//               "induty": "일반야영장,자동차야영장",
//               "lctCl": "산",
//               "doNm": "강원도",
//               "sigunguNm": "인제군",
//               "zipcode": "24643",
//               "addr1": "강원 인제군 인제읍 필례약수길 84-10",
//               "addr2": "",
//               "mapX": "128.3690179",
//               "mapY": "38.0762331",
//               "direction": "",
//               "tel": "033-463-0901",
//               "homepage": "http://www.oasisjungle.com",
//               "resveUrl": "",
//               "resveCl": "온라인실시간예약",
//               "manageNmpr": "0",
//               "gnrlSiteCo": "31",
//               "autoSiteCo": "21",
//               "glampSiteCo": "0",
//               "caravSiteCo": "0",
//               "indvdlCaravSiteCo": "0",
//               "sitedStnc": "0",
//               "siteMg1Width": "0",
//               "siteMg2Width": "0",
//               "siteMg3Width": "0",
//               "siteMg1Vrticl": "0",
//               "siteMg2Vrticl": "0",
//               "siteMg3Vrticl": "0",
//               "siteMg1Co": "0",
//               "siteMg2Co": "0",
//               "siteMg3Co": "0",
//               "siteBottomCl1": "0",
//               "siteBottomCl2": "45",
//               "siteBottomCl3": "0",
//               "siteBottomCl4": "7",
//               "siteBottomCl5": "0",
//               "tooltip": "",
//               "glampInnerFclty": "",
//               "caravInnerFclty": "",
//               "prmisnDe": "2021-11-30",
//               "operPdCl": "봄,여름,가을,겨울",
//               "operDeCl": "평일+주말",
//               "trlerAcmpnyAt": "Y",
//               "caravAcmpnyAt": "N",
//               "toiletCo": "0",
//               "swrmCo": "0",
//               "wtrplCo": "0",
//               "brazierCl": "개별",
//               "sbrsCl": "전기,무선인터넷,장작판매,온수,트렘폴린,운동시설",
//               "sbrsEtc": "",
//               "posblFcltyCl": "계곡 물놀이",
//               "posblFcltyEtc": "",
//               "clturEventAt": "N",
//               "clturEvent": "",
//               "exprnProgrmAt": "N",
//               "exprnProgrm": "",
//               "extshrCo": "0",
//               "frprvtWrppCo": "0",
//               "frprvtSandCo": "0",
//               "fireSensorCo": "0",
//               "themaEnvrnCl": "봄꽃여행,가을단풍명소",
//               "eqpmnLendCl": "",
//               "animalCmgCl": "가능(소형견)",
//               "tourEraCl": "",
//               "firstImageUrl": "https://gocamping.or.kr/upload/camp/100198/thumb/thumb_720_07734IcENf6mkpjuMAsrDSzV.jpg",
//               "createdtime": "2023-01-16 16:49:14",
//               "modifiedtime": "2023-01-16 16:49:14"
//             },
            
//           ]
//         },
//         "numOfRows": 20,
//         "pageNo": 10,
//         "totalCount": 3800
//       }
//     }
//   }