import React
 from "react";
 export const dummyList = {
    "response": {
      "header": {
        "resultCode": "0000",
        "resultMsg": "OK"
      },
      "body": {
        "items": {
          "item": [
            {
              "contentId": "10",
              "facltNm": "(주)아웃오브파크",
              "lineIntro": "이국적인 캐러밴과 알찬 부대시설",
              "intro": "아웃오브파트는 강원도 춘천시 남면에 자리했다. 서울양양고속도로 강촌IC에서 엘리시안강촌 방면으로 30분가량 달리면 도착한다. 이곳은 북한강 변의 수려한 풍광을 배경으로 캐러밴 40대가 들어찼다. 고급스러움이 돋보이는 유럽피안 캐러밴과 에어스트림 캐러밴이다. 모든 캐러밴은 각기 다른 주제로 꾸몄다. 이 덕분에 욕실에 중점을 둔 객실이나 침실에 초점을 맞춘 객실 등 취향에 따라 선택하는 재미가 있다. 외부에는 어닝 아래 테이블, 의자, 노천욕탕, 바비큐 시설을 마련했다. 캠핑장의 강점 중 하나는 부대시설이다. 카페, 수영장, 찜질방, 스파, 중앙 무대, 분수, 노래방 등 고급스러움으로 치장한 시설이 차고 넘친다.",
              "allar": "0",
              "insrncAt": "Y",
              "trsagntNo": "",
              "bizrno": "",
              "facltDivNm": "민간",
              "mangeDivNm": "직영",
              "mgcDiv": "",
              "manageSttus": "운영",
              "hvofBgnde": "",
              "hvofEnddle": "",
              "featureNm": "",
              "induty": "카라반",
              "lctCl": "산,강",
              "doNm": "강원도",
              "sigunguNm": "춘천시",
              "zipcode": "24468",
              "addr1": "강원도 춘천시 남면 가옹개길 52-9",
              "addr2": "",
              "mapX": "127.5112565",
              "mapY": "37.7278127",
              "direction": "울양양고속도로 강촌IC에서 엘리시안강촌 방면으로 30분가량 달리면 도착",
              "tel": "1522-1861-",
              "homepage": "http://outofpark.com/main/",
              "resveUrl": "",
              "resveCl": "온라인실시간예약",
              "manageNmpr": "0",
              "gnrlSiteCo": "0",
              "autoSiteCo": "0",
              "glampSiteCo": "0",
              "caravSiteCo": "40",
              "indvdlCaravSiteCo": "0",
              "sitedStnc": "0",
              "siteMg1Width": "0",
              "siteMg2Width": "0",
              "siteMg3Width": "0",
              "siteMg1Vrticl": "0",
              "siteMg2Vrticl": "0",
              "siteMg3Vrticl": "0",
              "siteMg1Co": "0",
              "siteMg2Co": "0",
              "siteMg3Co": "0",
              "siteBottomCl1": "0",
              "siteBottomCl2": "0",
              "siteBottomCl3": "0",
              "siteBottomCl4": "0",
              "siteBottomCl5": "0",
              "tooltip": "주변에는 쁘띠프랑스, 호명호수공원, 청평호반 등이 있어 연계 관광이 용이하다. 전통손두부닭갈비, 수림닭갈비 등 음식점도 많다.",
              "glampInnerFclty": "",
              "caravInnerFclty": "침대,TV,에어컨,냉장고,난방기구,취사도구,내부화장실",
              "prmisnDe": "2017-09-18",
              "operPdCl": "봄,여름,가을,겨울",
              "operDeCl": "평일+주말",
              "trlerAcmpnyAt": "N",
              "caravAcmpnyAt": "N",
              "toiletCo": "0",
              "swrmCo": "0",
              "wtrplCo": "0",
              "brazierCl": "개별",
              "sbrsCl": "운동시설",
              "sbrsEtc": "수영장, 노래방, 찜질방, 카페, 중앙 무대, 분수",
              "posblFcltyCl": "수영장",
              "posblFcltyEtc": "",
              "clturEventAt": "N",
              "clturEvent": "",
              "exprnProgrmAt": "N",
              "exprnProgrm": "",
              "extshrCo": "0",
              "frprvtWrppCo": "0",
              "frprvtSandCo": "0",
              "fireSensorCo": "0",
              "themaEnvrnCl": "",
              "eqpmnLendCl": "",
              "animalCmgCl": "불가능",
              "tourEraCl": "봄,여름,가을,겨울",
              "firstImageUrl": "https://gocamping.or.kr/upload/camp/10/thumb/thumb_720_1869epdMHtUyrinZWKFHDWty.jpg",
              "createdtime": "2023-01-16 16:44:46",
              "modifiedtime": "2024-03-29 06:30:06"
            },
            {
              "contentId": "100000",
              "facltNm": "파크킹",
              "lineIntro": "",
              "intro": "",
              "allar": "0",
              "insrncAt": "Y",
              "trsagntNo": "",
              "bizrno": "",
              "facltDivNm": "민간",
              "mangeDivNm": "직영",
              "mgcDiv": "",
              "manageSttus": "운영",
              "hvofBgnde": "",
              "hvofEnddle": "",
              "featureNm": "수영장, 카페 등 부대시설이 알찬 곳  파크킹은 경북 김천시 어모면 중왕리에 자리 잡았다. 김천시청을 기점으로 6km가량 떨어졌다. 자동차를 타고 어모로와 은림로를 번갈아 달리면 닿는다. 도착까지 걸리는 시간은 10분 안팎이다. 캠핑장에는 자갈로 이뤄진 일반캠핑 사이트 32면이 마련돼 있다. 사이트 크기는 가로 10m 세로 2m 등이다. 피크닉장도 운영 중이다. 외부음식 가지고 입장할 수 있으며, 취사도 가능하다. 수영장, 카페, 산책로 등 부대시설도 알차게 갖춰져 있다. 주변에는 김천자산동벽화마을이 있어 연계 여행에 나서기 편하다.",
              "induty": "자동차야영장",
              "lctCl": "숲",
              "doNm": "경상북도",
              "sigunguNm": "김천시",
              "zipcode": "39504",
              "addr1": "경북 김천시 어모면 은림로 62-11",
              "addr2": "",
              "mapX": "128.1270051",
              "mapY": "36.1795215",
              "direction": "",
              "tel": "054-434-6677",
              "homepage": "https://www.instagram.com/amazingpark6211/",
              "resveUrl": "https://pf.kakao.com/_YAtks",
              "resveCl": "온라인실시간예약",
              "manageNmpr": "2",
              "gnrlSiteCo": "31",
              "autoSiteCo": "0",
              "glampSiteCo": "0",
              "caravSiteCo": "0",
              "indvdlCaravSiteCo": "1",
              "sitedStnc": "0",
              "siteMg1Width": "0",
              "siteMg2Width": "0",
              "siteMg3Width": "0",
              "siteMg1Vrticl": "0",
              "siteMg2Vrticl": "0",
              "siteMg3Vrticl": "0",
              "siteMg1Co": "15",
              "siteMg2Co": "17",
              "siteMg3Co": "0",
              "siteBottomCl1": "3",
              "siteBottomCl2": "0",
              "siteBottomCl3": "0",
              "siteBottomCl4": "29",
              "siteBottomCl5": "0",
              "tooltip": "",
              "glampInnerFclty": "",
              "caravInnerFclty": "",
              "prmisnDe": "2021-07-31",
              "operPdCl": "봄,여름,가을,겨울",
              "operDeCl": "평일+주말",
              "trlerAcmpnyAt": "Y",
              "caravAcmpnyAt": "N",
              "toiletCo": "6",
              "swrmCo": "2",
              "wtrplCo": "2",
              "brazierCl": "개별",
              "sbrsCl": "전기,무선인터넷,장작판매,온수,트렘폴린,물놀이장,놀이터,산책로,운동장,운동시설,마트.편의점",
              "sbrsEtc": "",
              "posblFcltyCl": "산책로",
              "posblFcltyEtc": "",
              "clturEventAt": "N",
              "clturEvent": "",
              "exprnProgrmAt": "N",
              "exprnProgrm": "",
              "extshrCo": "20",
              "frprvtWrppCo": "0",
              "frprvtSandCo": "0",
              "fireSensorCo": "0",
              "themaEnvrnCl": "여름물놀이,걷기길",
              "eqpmnLendCl": "",
              "animalCmgCl": "가능",
              "tourEraCl": "",
              "firstImageUrl": "https://gocamping.or.kr/upload/camp/100000/thumb/thumb_720_8961mOX5pkL8PIG296E1RU3S.jpg",
              "createdtime": "2023-01-16 16:48:52",
              "modifiedtime": "2023-01-16 16:48:52"
            },
            {
              "contentId": "100001",
              "facltNm": "봉즈살롱",
              "lineIntro": "",
              "intro": "",
              "allar": "0",
              "insrncAt": "Y",
              "trsagntNo": "",
              "bizrno": "",
              "facltDivNm": "민간",
              "mangeDivNm": "직영",
              "mgcDiv": "",
              "manageSttus": "운영",
              "hvofBgnde": "",
              "hvofEnddle": "",
              "featureNm": "베이커리 카페와 함께하는 회원제 야영장  베어키리 카페를 겸하고 있는 작은 캠핑장으로 회원제로 운영된다. 카페 바로 옆의 잔디밭과 마당에 있는 나무숲이 야영장으로 사용된다. 또한 카페 바로 옆으로 주변에서 소문난 식당이 함께 있고 작은 수영장도 운영한다. 야영장 앞에는 약사천이 흘러 개울에서 물놀이도 할 수 있다.",
              "induty": "자동차야영장",
              "lctCl": "강",
              "doNm": "강원도",
              "sigunguNm": "횡성군",
              "zipcode": "25202",
              "addr1": "강원 횡성군 서원면 서원서로102번길 3-18",
              "addr2": "",
              "mapX": "127.8240705696189",
              "mapY": "37.48049694689978",
              "direction": "",
              "tel": "033-345-3336",
              "homepage": "https://www.instagram.com/salon.de.bonj/",
              "resveUrl": "",
              "resveCl": "온라인예약대기",
              "manageNmpr": "0",
              "gnrlSiteCo": "7",
              "autoSiteCo": "0",
              "glampSiteCo": "0",
              "caravSiteCo": "0",
              "indvdlCaravSiteCo": "0",
              "sitedStnc": "0",
              "siteMg1Width": "0",
              "siteMg2Width": "0",
              "siteMg3Width": "0",
              "siteMg1Vrticl": "0",
              "siteMg2Vrticl": "0",
              "siteMg3Vrticl": "0",
              "siteMg1Co": "7",
              "siteMg2Co": "0",
              "siteMg3Co": "0",
              "siteBottomCl1": "0",
              "siteBottomCl2": "7",
              "siteBottomCl3": "0",
              "siteBottomCl4": "0",
              "siteBottomCl5": "0",
              "tooltip": "",
              "glampInnerFclty": "",
              "caravInnerFclty": "",
              "prmisnDe": "2021-07-30",
              "operPdCl": "봄,여름,가을,겨울",
              "operDeCl": "평일+주말",
              "trlerAcmpnyAt": "N",
              "caravAcmpnyAt": "N",
              "toiletCo": "0",
              "swrmCo": "0",
              "wtrplCo": "0",
              "brazierCl": "개별",
              "sbrsCl": "전기,무선인터넷,물놀이장",
              "sbrsEtc": "카페",
              "posblFcltyCl": "계곡 물놀이",
              "posblFcltyEtc": "",
              "clturEventAt": "N",
              "clturEvent": "",
              "exprnProgrmAt": "N",
              "exprnProgrm": "",
              "extshrCo": "0",
              "frprvtWrppCo": "0",
              "frprvtSandCo": "0",
              "fireSensorCo": "0",
              "themaEnvrnCl": "",
              "eqpmnLendCl": "",
              "animalCmgCl": "불가능",
              "tourEraCl": "",
              "firstImageUrl": "https://gocamping.or.kr/upload/camp/100001/thumb/thumb_720_8208rbdo3oMU3WFnqwsHtWjt.jpg",
              "createdtime": "2023-01-16 16:48:52",
              "modifiedtime": "2023-01-16 16:48:52"
            },
            {
              "contentId": "100002",
              "facltNm": "힐링피아 카라반 글램핑 풀 캠핑장",
              "lineIntro": "별보기 좋은 카라반 캠핑장",
              "intro": "힐링피아 카라반 글램핑 풀 캠핑장은 어비계곡 사기막천과 유명산 벽계천이 합류하는 두물머리에 위치하고 있다. 카라반 데크의 크기는 휴식공간용과 바베큐공간을 분리 할 정도의 넓은 공간이고 각 카라반에 개별 수영장이 있다. 놀이시설로는 개별수영장 별도의 야외수영장, 어린이 암벽 ,하늘자전거,탁구대 등이 있으며, 힐링하기 좋은 전망대가 있어 밤에 별보기 좋은 카라반 캠핑장이다.",
              "allar": "6600",
              "insrncAt": "Y",
              "trsagntNo": "2017-6",
              "bizrno": "169-52-00647",
              "facltDivNm": "민간",
              "mangeDivNm": "직영",
              "mgcDiv": "허동석",
              "manageSttus": "운영",
              "hvofBgnde": "",
              "hvofEnddle": "",
              "featureNm": "어비계곡 하류 합수점에 위치한 풀빌라형 카라반  힐링피아 카라반 글램핑 풀 캠핑장은 어비계곡 사기막천과 유명산 벽계천이 합류하는 두물머리에 위치하고 있다. 카라반 데크의 크기는 휴식공간용과 바베큐공간을 분리 할 정도의 넓은 공간이고 각 카라반에 개별 수영장이 있다. 놀이시설로는 개별수영장 별도의 야외수영장, 어린이 암벽 ,하늘자전거,탁구대 등이 있으며, 힐링하기 좋은 전망대가 있어 밤에 별보기 좋은 카라반 캠핑장이다. ",
              "induty": "일반야영장",
              "lctCl": "산,숲,강",
              "doNm": "경기도",
              "sigunguNm": "가평군",
              "zipcode": "12473",
              "addr1": "경기 가평군 설악면 유명산길 61-75",
              "addr2": "",
              "mapX": "127.4947241",
              "mapY": "37.5978864",
              "direction": "",
              "tel": "010-3148-9970",
              "homepage": "http://healingpia.co.kr",
              "resveUrl": "http://healingpia.co.kr",
              "resveCl": "온라인실시간예약",
              "manageNmpr": "3",
              "gnrlSiteCo": "1",
              "autoSiteCo": "0",
              "glampSiteCo": "0",
              "caravSiteCo": "15",
              "indvdlCaravSiteCo": "0",
              "sitedStnc": "0",
              "siteMg1Width": "0",
              "siteMg2Width": "0",
              "siteMg3Width": "0",
              "siteMg1Vrticl": "0",
              "siteMg2Vrticl": "0",
              "siteMg3Vrticl": "0",
              "siteMg1Co": "0",
              "siteMg2Co": "0",
              "siteMg3Co": "0",
              "siteBottomCl1": "0",
              "siteBottomCl2": "0",
              "siteBottomCl3": "15",
              "siteBottomCl4": "0",
              "siteBottomCl5": "0",
              "tooltip": "",
              "glampInnerFclty": "",
              "caravInnerFclty": "",
              "prmisnDe": "2021-05-10",
              "operPdCl": "봄,여름,가을,겨울",
              "operDeCl": "평일+주말",
              "trlerAcmpnyAt": "N",
              "caravAcmpnyAt": "N",
              "toiletCo": "3",
              "swrmCo": "2",
              "wtrplCo": "4",
              "brazierCl": "개별",
              "sbrsCl": "전기,무선인터넷,장작판매,온수,마트.편의점",
              "sbrsEtc": "",
              "posblFcltyCl": "계곡 물놀이,산책로,강/물놀이,수영장,청소년체험시설",
              "posblFcltyEtc": "",
              "clturEventAt": "N",
              "clturEvent": "",
              "exprnProgrmAt": "N",
              "exprnProgrm": "",
              "extshrCo": "20",
              "frprvtWrppCo": "1",
              "frprvtSandCo": "1",
              "fireSensorCo": "15",
              "themaEnvrnCl": "액티비티,봄꽃여행,여름물놀이,가을단풍명소,겨울눈꽃명소,걷기길",
              "eqpmnLendCl": "",
              "animalCmgCl": "불가능",
              "tourEraCl": "봄,여름,가을,겨울",
              "firstImageUrl": "https://gocamping.or.kr/upload/camp/100002/thumb/thumb_720_20339geHYKzGA9OjsoC0nFwX.jpg",
              "createdtime": "2023-01-16 16:48:53",
              "modifiedtime": "2023-01-16 16:48:53"
            },
            {
              "contentId": "100003",
              "facltNm": "우니메이카 태안점",
              "lineIntro": "",
              "intro": "우니메이카 태안점은 숲속 야영장으로 15개의 데크, 8개의 개별화장실을 보유하고 있으며 오래자란 소나무숲 그늘이 풍부하고 약5킬로거리에 서해안 최고의 만리포해수욕장과 모항항이 있어 숲과 바다를 함께 즐길 수있는 장점이 있습니다.",
              "allar": "0",
              "insrncAt": "Y",
              "trsagntNo": "2021-6",
              "bizrno": "275-46-00714",
              "facltDivNm": "민간",
              "mangeDivNm": "직영",
              "mgcDiv": "강희권",
              "manageSttus": "운영",
              "hvofBgnde": "",
              "hvofEnddle": "",
              "featureNm": "쭉 머물고픈 깊은 숲속 요새 같은 캠핑장  우니메이카 태안점은 충남 태안군 소원면 신덕리에 자리 잡았다. 태안군청을 기점으로 15km가량 떨어졌다. 자동차를 타고 서해로와 산간이길을 번갈아 달리면 닿는다. 도착까지 걸리는 시간은 20분 안팎이다. 캠핑장은 깊은 숲속에 위치하고 있어 요새 같은 느낌이다. 데크로 이뤄진 일반캠핑 사이트 15면이 마련돼 있으며, 사이트 크기는 가로 4m 세로 4m다. 사이트 간격이 무척 넓어 프라이빗한 캠핑을 만끽할 수 있다. 솔로 캠핑이나 미니멀 캠핑을 즐기는 캠퍼들이 열광할 만한 조건을 갖춘 셈이다. 게다가 개별 화장실과 샤워실을 사용할 수 있어 편리하다. 주변에는 만리포해수욕장과 만리포항이 있어 연계 관광에 나서기 수월하다.",
              "induty": "자동차야영장",
              "lctCl": "숲",
              "doNm": "충청남도",
              "sigunguNm": "태안군",
              "zipcode": "32120",
              "addr1": "충남 태안군 소원면 산간이길 158-24",
              "addr2": "",
              "mapX": "126.1890914",
              "mapY": "36.7796484",
              "direction": "",
              "tel": "043-1668-3972",
              "homepage": "",
              "resveUrl": "https://map.naver.com/v5/entry/place/1791561655?c=14047305.3983138,4408436.9604705,15,0,0,0,dh&placePath=%2Fbooking%3Fentry=plt",
              "resveCl": "전화",
              "manageNmpr": "1",
              "gnrlSiteCo": "15",
              "autoSiteCo": "0",
              "glampSiteCo": "0",
              "caravSiteCo": "0",
              "indvdlCaravSiteCo": "0",
              "sitedStnc": "3",
              "siteMg1Width": "0",
              "siteMg2Width": "0",
              "siteMg3Width": "0",
              "siteMg1Vrticl": "0",
              "siteMg2Vrticl": "0",
              "siteMg3Vrticl": "0",
              "siteMg1Co": "15",
              "siteMg2Co": "0",
              "siteMg3Co": "0",
              "siteBottomCl1": "0",
              "siteBottomCl2": "0",
              "siteBottomCl3": "15",
              "siteBottomCl4": "0",
              "siteBottomCl5": "0",
              "tooltip": "",
              "glampInnerFclty": "",
              "caravInnerFclty": "",
              "prmisnDe": "2021-07-21",
              "operPdCl": "봄,여름,가을,겨울",
              "operDeCl": "평일+주말",
              "trlerAcmpnyAt": "N",
              "caravAcmpnyAt": "N",
              "toiletCo": "15",
              "swrmCo": "15",
              "wtrplCo": "1",
              "brazierCl": "개별",
              "sbrsCl": "전기,장작판매,온수,놀이터,운동시설",
              "sbrsEtc": "",
              "posblFcltyCl": "수상레저,낚시,해수욕",
              "posblFcltyEtc": "",
              "clturEventAt": "N",
              "clturEvent": "",
              "exprnProgrmAt": "N",
              "exprnProgrm": "",
              "extshrCo": "16",
              "frprvtWrppCo": "1",
              "frprvtSandCo": "1",
              "fireSensorCo": "1",
              "themaEnvrnCl": "봄꽃여행,가을단풍명소,겨울눈꽃명소",
              "eqpmnLendCl": "화로대",
              "animalCmgCl": "가능",
              "tourEraCl": "",
              "firstImageUrl": "https://gocamping.or.kr/upload/camp/100003/thumb/thumb_720_6517S9GUDxExcoVxf6fWGCxC.jpg",
              "createdtime": "2023-01-16 16:48:53",
              "modifiedtime": "2023-01-16 16:48:53"
            }
          ]
        },
        "numOfRows": 5,
        "pageNo": 1,
        "totalCount": 3801
      }
    }
  };